-- luacheck: globals vim
-- luacheck: ignore 113
local lush = require("lush")
local colors = require("lushwal").colors
return lush(function()
	-- selene: allow(undefined_variable)
	return {
		TSAnnotation({ fg = colors.color4 }),
		TSAttribute({ fg = colors.color4 }),
		TSBoolean({ fg = colors.color4 }),
		TSCharacter({ fg = colors.color3 }),
		TSComment({ fg = colors.color7, gui = "italic" }),
		TSConditional({ fg = colors.color5 }),
		TSConstBuiltin({ fg = colors.color1 }),
		TSConstMacro({ fg = colors.color1 }),
		TSConstant({ fg = colors.color1 }),
		TSConstructor({ fg = colors.foreground }),
		TSEmphasis({ gui = "italic", fg = colors.purple }),
		TSError({ fg = colors.color5 }),
		TSException({ fg = colors.color5 }),
		TSField({ fg = colors.color2 }),
		TSFloat({ fg = colors.color4 }),
		TSFuncBuiltin({ fg = colors.color1 }),
		TSFuncMacro({ fg = colors.color1 }),
		TSFunction({ fg = colors.color4 }),
		TSInclude({ fg = colors.color6 }),
		TSKeyword({ fg = colors.purple }),
		TSKeywordFunction({ fg = colors.color6 }),
		TSKeywordOperator({ fg = colors.purple }),
		TSLabel({ fg = colors.color6 }),
		TSMethod({ fg = colors.color4 }),
		TSNamespace({ fg = colors.color4 }),
		TSNumber({ fg = colors.color4 }),
		TSOperator({ fg = colors.foreground }),
		TSParameter({ fg = colors.color3 }),
		TSParameterReference({ fg = colors.color1 }),
		TSProperty({ fg = colors.color3 }),
		TSPunctBracket({ fg = colors.foreground }),
		TSPunctDelimiter({ fg = colors.foreground }),
		TSPunctSpecial({ fg = colors.color14, gui = "bold" }),
		TSRepeat({ fg = colors.color5 }),
		TSString({ fg = colors.color4 }),
		TSStringEscape({ fg = colors.color2 }),
		TSStringRegex({ fg = colors.color2 }),
		TSStrong({ gui = "bold", fg = colors.color3 }),
		TSStructure({ fg = colors.color4 }),
		TSTag({ fg = colors.color3 }),
		TSTagDelimiter({ fg = colors.color6 }),
		TSText({ fg = colors.color2 }),
		TSType({ fg = colors.color4 }),
		TSTypeBuiltin({ fg = colors.color4 }),
		TSURI({ gui = "underline", bg = colors.color8 }),
		TSUnderline({ gui = "underline" }),
		TSVariable({ fg = colors.color3 }),
		TSVariableBuiltin({ fg = colors.color5 }),
	}
	-- selene: deny(undefined_variable)
end)
